model_name: "resnet50"
model_cfg:
  weights:

input_shape: [1, 3, 512, 512]
use_half: True
use_cuda: True
top_k: 30
target_modules:
  - "Conv2d"
  - "Conv1d"
  - "Linear"
  # - "ReLU"
  # - "BatchNorm2d"
save_dir: "results"
