model_name: "resnet152"
model_cfg:
  weights:

input_shape: [1, 3, 224, 224]
use_cuda: True
worst_k: 10
target_modules:
  - "Conv2d"
  # - "Conv1d"
  # - "Linear"
  # - "ReLU"
  # - "BatchNorm2d"
save_dir: "results"
